"""Unified inverse-decoder finetuning (the paper's key experiment #1).

We finetune a model's encoder so that it approximates the inverse of the decoder
*on images generated by that model*. Concretely, for a generated image whose
quantized feature map is ``f_Z`` (the target the AR tokens were sampled from), we
minimize

    L_inv = || f_Z - encode_feature(D(f_Z)) ||            (feature term)
          [ + img_w   * || D(f_Z) - D(encode_feature(D(f_Z))) || ]   (optional)
          [ + lpips_w * LPIPS(...) ]                                  (optional)

with the decoder and codebook frozen. Generated images are produced once by
``scripts/generate_data.py`` (which saves each ``f_Z`` as ``*_target.pt``).

For RAR and Taming we optionally enable a progressive weak->medium->strong
augmentation schedule (``augment=True``): the augmentation is applied to the
generated image *before* re-encoding, while the target ``f_Z`` stays the
un-augmented one. This trains the inverse decoder to recover the original tokens
even from post-processed images, which is what makes QuantLoss robust.
"""

from __future__ import annotations

import os
from typing import List, Optional, Tuple

import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from tqdm import tqdm

from . import augmentations as A
from .data import GeneratedTargetDataset
from .models.base import BaseIAR

__all__ = ["finetune_inverse_decoder"]


def _build_optimizer(params, cfg):
    name = str(cfg.get("optimizer", "adam")).lower()
    lr = float(cfg.get("lr", 1e-4))
    wd = float(cfg.get("weight_decay", 0.0))
    betas = tuple(cfg.get("betas", (0.9, 0.999)))
    if name == "adam":
        return torch.optim.Adam(params, lr=lr, betas=betas, weight_decay=wd)
    if name == "adamw":
        return torch.optim.AdamW(params, lr=lr, betas=betas, weight_decay=wd)
    raise ValueError(f"Unknown optimizer '{name}'")


def _build_scheduler(optimizer, cfg, total_steps: int):
    sch = cfg.get("scheduler", None)
    if sch is None:
        return None
    name = str(sch.get("name", "")).lower()
    if name in ("", "none"):
        return None
    if name == "steplr":
        return torch.optim.lr_scheduler.StepLR(
            optimizer, step_size=int(sch.get("step_size", 2)), gamma=float(sch.get("gamma", 0.9))
        )
    if name == "cosine":
        return torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=total_steps)
    raise ValueError(f"Unknown scheduler '{name}'")


def finetune_inverse_decoder(
    model: BaseIAR,
    data_dir: str,
    out_dir: str,
    cfg,
    augment: bool = False,
    aug_schedule: Optional[List[Tuple[str, int]]] = None,
    aug_p: float = 0.5,
    limit: Optional[int] = None,
    save_every: int = 1,
    log_every: int = 50,
) -> str:
    """Run finetuning and return the path of the final saved encoder.

    ``cfg`` is the ``finetune`` section of a model config (see ``configs/*.yaml``).
    """
    os.makedirs(out_dir, exist_ok=True)
    device = model.device

    epochs = int(cfg.get("epochs", 25))
    batch_size = int(cfg.get("batch_size", 8))
    feat_w = float(cfg.get("feat_weight", 1.0))
    img_w = float(cfg.get("img_weight", 0.0))
    lpips_w = float(cfg.get("lpips_weight", 0.0))
    grad_clip = float(cfg.get("grad_clip", 0.0))

    dataset = GeneratedTargetDataset(data_dir, model.image_transform(), limit=limit)
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=int(cfg.get("num_workers", 4)),
        drop_last=True,
        pin_memory=True,
    )

    # Freeze everything, then unfreeze the encoder modules to finetune.
    for p in model.parameters():
        p.requires_grad_(False)
    trainable: List[torch.nn.Parameter] = []
    for m in model.trainable_encoder_modules():
        m.train()
        for p in m.parameters():
            p.requires_grad_(True)
            trainable.append(p)

    optimizer = _build_optimizer(trainable, cfg)
    scheduler = _build_scheduler(optimizer, cfg, total_steps=epochs * len(loader))

    lpips_fn = None
    if lpips_w > 0:
        import lpips as lpips_lib  # noqa: WPS433 (optional dependency)

        lpips_fn = lpips_lib.LPIPS(net="vgg").to(device).eval()

    if augment and aug_schedule is None:
        # Default: 1 warmup / 1 weak / 4 medium / 4 strong, scaled to epochs.
        aug_schedule = _default_schedule(epochs)

    final_path = os.path.join(out_dir, "encoder_final.pth")
    for epoch in range(epochs):
        stage = A.stage_for_epoch(epoch, aug_schedule) if augment else None
        running = 0.0
        pbar = tqdm(loader, desc=f"epoch {epoch + 1}/{epochs}" + (f" [{stage}]" if augment else ""))
        for step, (img01, target) in enumerate(pbar):
            img01 = img01.to(device)
            target = target.to(device)

            clean_native = model.to_model_range(img01)
            if stage is not None:
                aug01 = A.sample_train_augmentation(img01, stage, p=aug_p)
                enc_input = model.to_model_range(aug01.to(device))
            else:
                enc_input = clean_native

            pred = model.encode_feature(enc_input)
            loss = feat_w * F.mse_loss(pred, target.to(pred.dtype))

            if img_w > 0 or lpips_w > 0:
                rec = model.decode_feature(pred)
                if img_w > 0:
                    loss = loss + img_w * F.mse_loss(rec, clean_native)
                if lpips_w > 0:
                    loss = loss + lpips_w * lpips_fn(rec, clean_native).mean()

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            if grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(trainable, grad_clip)
            optimizer.step()

            running += loss.item()
            if (step + 1) % log_every == 0:
                pbar.set_postfix(loss=f"{running / (step + 1):.5f}")

        print(f"epoch {epoch + 1}/{epochs}: avg_loss={running / max(1, len(loader)):.6f}")
        if scheduler is not None:
            scheduler.step()

        if (epoch + 1) % save_every == 0 or (epoch + 1) == epochs:
            ckpt = os.path.join(out_dir, f"encoder_epoch_{epoch + 1}.pth")
            torch.save(model.encoder_state_dict(), ckpt)
            torch.save(model.encoder_state_dict(), final_path)
            print(f"saved {ckpt}")

    return final_path


def _default_schedule(epochs: int) -> List[Tuple[str, int]]:
    """Distribute epochs across none/weak/medium/strong stages (ratio 1:1:4:4)."""
    if epochs <= 4:
        return [("none", epochs)]
    unit = max(1, epochs // 10)
    none_e = unit
    weak_e = unit
    medium_e = 4 * unit
    strong_e = epochs - none_e - weak_e - medium_e
    return [("none", none_e), ("weak", weak_e), ("medium", medium_e), ("strong", strong_e)]
