"""Detection metrics for data provenance.

We frame provenance as a binary separation between a *belonging* set (images
generated by the target model, a.k.a. members) and a *non-belonging* set
(natural images or images from other models). The primary metric reported in
the paper is the True Positive Rate at a 1% False Positive Rate
(``TPR@1%FPR``).

For all of our signals (QuantLoss, EncLoss, Combined Loss) belonging images
have a *lower* score than non-belonging images, hence ``members_lower=True`` is
the default throughout.

The implementation mirrors the evaluation used in the original codebase.
"""

from __future__ import annotations

from typing import Tuple

import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve

__all__ = [
    "scale_and_order",
    "tpr_at_fpr",
    "auc",
    "accuracy",
]


def _asserts(members: np.ndarray, nonmembers: np.ndarray) -> None:
    assert members.ndim == 1 and nonmembers.ndim == 1, "scores must be 1-D arrays"
    assert members.shape[0] > 0 and nonmembers.shape[0] > 0, "empty score array"


def scale_and_order(
    members: np.ndarray, nonmembers: np.ndarray, members_lower: bool
) -> Tuple[np.ndarray, np.ndarray]:
    """Scale scores to ``[0, 1]`` and flip them so that members score *higher*.

    ``roc_curve`` expects larger scores for the positive class. Our losses are
    smaller for members, so when ``members_lower`` is set we invert the scaled
    scores. Scaling by the shared maximum keeps both sets on the same axis.
    """
    members = np.asarray(members, dtype=np.float64)
    nonmembers = np.asarray(nonmembers, dtype=np.float64)

    max_score = max(np.max(members), np.max(nonmembers))
    max_score = 1e-6 if max_score == 0 else max_score
    members = members / max_score
    nonmembers = nonmembers / max_score

    if members_lower:
        members = 1.0 - members
        nonmembers = 1.0 - nonmembers
    return members, nonmembers


def _y_true_y_score(
    members: np.ndarray, nonmembers: np.ndarray
) -> Tuple[np.ndarray, np.ndarray]:
    y_true = np.concatenate([np.ones_like(members), np.zeros_like(nonmembers)])
    y_score = np.concatenate([members, nonmembers])
    return y_true, y_score


def tpr_at_fpr(
    members: np.ndarray,
    nonmembers: np.ndarray,
    fpr_threshold: float = 0.01,
    members_lower: bool = True,
) -> float:
    """True positive rate at a given false positive rate.

    Returns the TPR at the largest operating point whose FPR does not exceed
    ``fpr_threshold`` (1% by default).
    """
    _asserts(members, nonmembers)
    assert 0.0 <= fpr_threshold <= 1.0
    members, nonmembers = scale_and_order(members, nonmembers, members_lower)
    y_true, y_score = _y_true_y_score(members, nonmembers)
    fpr, tpr, _ = roc_curve(y_true, y_score)
    return float(tpr[np.sum(fpr <= fpr_threshold) - 1])


def auc(
    members: np.ndarray, nonmembers: np.ndarray, members_lower: bool = True
) -> float:
    """Area under the ROC curve."""
    _asserts(members, nonmembers)
    members, nonmembers = scale_and_order(members, nonmembers, members_lower)
    y_true, y_score = _y_true_y_score(members, nonmembers)
    return float(roc_auc_score(y_true, y_score))


def accuracy(
    members: np.ndarray, nonmembers: np.ndarray, members_lower: bool = True
) -> float:
    """Best balanced accuracy at the 0.5 threshold of the scaled scores."""
    _asserts(members, nonmembers)
    members, nonmembers = scale_and_order(members, nonmembers, members_lower)
    y_true, y_score = _y_true_y_score(members, nonmembers)
    return float(np.mean((y_score > 0.5).astype(np.float64) == y_true))
