"""The three provenance signals: QuantLoss, EncLoss and Combined Loss.

Given a suspect image ``x`` and a target IAR model ``M`` (with inverse decoder
``D^{-1}``, codebook quantizer ``Q`` and decoder ``D``), we compute:

* **QuantLoss**  ``L_Z(x) = || f - f_Z ||``
  where ``f = D^{-1}(x)`` and ``f_Z = Q^{-1}(Q(f))``. Images generated by ``M``
  invert to feature maps that already lie close to codebook entries, so their
  quantization error is small.

* **EncLoss** (calibrated)  ``L_enc(x) = ||x_hat - x|| / ||x_hat_hat - x_hat||``
  where ``x_hat = D(D^{-1}(x))`` is the no-quantization reconstruction. The
  numerator is the information lost when compressing ``x`` into the latent
  space; the denominator calibrates for the intrinsic complexity of the image
  by reconstructing a second time (AEDR-style).

* **Combined Loss**  ``L_comb(x) = L_Z(x) * L_enc(x)``.

All three are returned per-sample. Belonging images score *lower* on every
signal.
"""

from __future__ import annotations

from typing import Dict

import numpy as np
import torch
from torch import Tensor
from torch.nn import functional as F

from .models.base import BaseIAR

__all__ = ["mse_per_sample", "provenance_signals", "SIGNAL_NAMES"]

#: Order in which signals are reported in tables.
SIGNAL_NAMES = ["reconstruction", "quant_loss", "enc_loss", "combined"]

_EPS = 1e-10


def mse_per_sample(a: Tensor, b: Tensor) -> Tensor:
    """Mean-squared error reduced over all but the batch dimension."""
    a = a.float()
    b = b.float()
    return F.mse_loss(a, b, reduction="none").flatten(1).mean(dim=1)


@torch.no_grad()
def provenance_signals(
    model: BaseIAR, images: Tensor, eps: float = _EPS
) -> Dict[str, np.ndarray]:
    """Compute every provenance signal for a batch of images.

    Parameters
    ----------
    model : BaseIAR
        The target model. Whether it uses the *original* or *finetuned* encoder
        is decided when the model is built (see ``--encoder`` in the scripts);
        running with the original encoder reproduces the ``Reconstruction`` and
        ``AEDR`` baselines.
    images : Tensor
        Batch ``(B, 3, H, W)`` in the model's native value range.

    Returns
    -------
    dict of ``{signal_name: (B,) np.ndarray}`` for keys in :data:`SIGNAL_NAMES`,
    plus ``enc_loss_uncalibrated`` (the raw first reconstruction error, i.e. the
    AEDR/Reconstruction baseline numerator).
    """
    images = images.to(model.device)

    # --- QuantLoss: ||f - f_Z|| with quantization (optimized search for VAR) ---
    rec_quant, _tokens, f, fhat = model.img_to_reconstructed_img(images, use_quant=True)
    quant_loss = mse_per_sample(f, fhat)

    # Naive reconstruction baseline: ||x - D(Q^{-1}(Q(D^{-1}(x))))||.
    reconstruction = mse_per_sample(rec_quant, images)

    # --- EncLoss: calibrated double-reconstruction ratio (no quantization) ---
    rec1, _, _, _ = model.img_to_reconstructed_img(images, use_quant=False)
    rec2, _, _, _ = model.img_to_reconstructed_img(rec1, use_quant=False)
    loss1 = mse_per_sample(rec1, images)
    loss2 = mse_per_sample(rec2, rec1)
    enc_loss = (loss1 + eps) / (loss2 + eps)

    combined = quant_loss * enc_loss

    return {
        "reconstruction": reconstruction.cpu().numpy(),
        "quant_loss": quant_loss.cpu().numpy(),
        "enc_loss": enc_loss.cpu().numpy(),
        "enc_loss_uncalibrated": loss1.cpu().numpy(),
        "combined": combined.cpu().numpy(),
    }
