"""Evaluate provenance: TPR@1%FPR of belonging vs non-belonging images.

Reproduces the main result table: for the target model, distinguish images it
generated (belonging) from images of natural datasets or other models
(non-belonging), reporting TPR@1%FPR for each signal.

Examples
--------
    # our method (finetuned inverse decoder), all signals
    python scripts/evaluate.py rar \
        --belonging   data/rar_generated \
        --nonbelonging data/imagenet data/llamagen_generated data/var_generated

    # baselines: Reconstruction + AEDR (original encoder) and LatentTracer
    python scripts/evaluate.py rar --encoder original --baselines \
        --belonging data/rar_generated --nonbelonging data/imagenet
"""

from __future__ import annotations

import argparse
import csv
import os
from typing import Dict, List

import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

from _common import build_from_args, add_common_args  # noqa: E402
from dataprov import metrics, signals  # noqa: E402
from dataprov.baselines import latent_tracer  # noqa: E402
from dataprov.data import ImageFolder  # noqa: E402


def folder_scores(model, folder, batch_size, limit, with_latent_tracer) -> Dict[str, np.ndarray]:
    ds = ImageFolder(folder, model.image_transform(), limit=limit)
    loader = DataLoader(ds, batch_size=batch_size, num_workers=4, shuffle=False)
    acc: Dict[str, List[np.ndarray]] = {}
    for img01 in tqdm(loader, desc=os.path.basename(folder.rstrip("/")), leave=False):
        native = model.to_model_range(img01.to(model.device))
        out = signals.provenance_signals(model, native)
        if with_latent_tracer:
            out["latent_tracer"] = latent_tracer(model, native)
        for k, v in out.items():
            acc.setdefault(k, []).append(v)
    return {k: np.concatenate(v) for k, v in acc.items()}


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    add_common_args(p)
    p.add_argument("--belonging", required=True, help="folder of images generated by the target model")
    p.add_argument("--nonbelonging", required=True, nargs="+", help="one or more folders of other images")
    p.add_argument("--signals", nargs="+", default=list(signals.SIGNAL_NAMES),
                   help="which signals to report")
    p.add_argument("--baselines", action="store_true",
                   help="also report the LatentTracer baseline")
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--limit", type=int, default=None, help="cap images per folder")
    p.add_argument("--out", default=None, help="optional CSV output path")
    args = p.parse_args()

    model, cfg = build_from_args(args)

    rows = list(args.signals) + (["latent_tracer"] if args.baselines else [])

    bel = folder_scores(model, args.belonging, args.batch_size, args.limit, args.baselines)
    table: Dict[str, Dict[str, float]] = {r: {} for r in rows}
    for nb in args.nonbelonging:
        non = folder_scores(model, nb, args.batch_size, args.limit, args.baselines)
        name = os.path.basename(nb.rstrip("/"))
        for r in rows:
            table[r][name] = 100.0 * metrics.tpr_at_fpr(bel[r], non[r], 0.01, members_lower=True)

    nb_names = [os.path.basename(nb.rstrip("/")) for nb in args.nonbelonging]
    width = max(14, *(len(n) for n in nb_names))
    print(f"\nTPR@1%FPR (%)  |  model={args.model}  encoder={args.encoder}\n")
    header = "signal".ljust(18) + "".join(n.rjust(width + 2) for n in nb_names)
    print(header)
    print("-" * len(header))
    for r in rows:
        line = r.ljust(18) + "".join(f"{table[r][n]:>{width + 2}.1f}" for n in nb_names)
        print(line)

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["signal"] + nb_names)
            for r in rows:
                w.writerow([r] + [f"{table[r][n]:.2f}" for n in nb_names])
        print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
